# Generated by Django 4.2.7 on 2026-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_dailyoffer_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
